/* user/web/history.c -- see history.h. */
#include <string.h>
#include <stdio.h>

#include "history.h"
#include "store.h"

#define HIST_MAX   64
#define URL_LEN   256
#define TITLE_LEN 128

static struct {
    char url[URL_LEN];
    char title[TITLE_LEN];
    unsigned long long when;
} g_h[HIST_MAX];
static int g_n;

int hist_count(void) { return g_n; }
const char *hist_url(int i)   { return (i >= 0 && i < g_n) ? g_h[i].url : 0; }
const char *hist_title(int i) { return (i >= 0 && i < g_n) ? g_h[i].title : 0; }
unsigned long long hist_when(int i) { return (i >= 0 && i < g_n) ? g_h[i].when : 0; }
void hist_clear(void) { g_n = 0; memset(g_h, 0, sizeof g_h); }

void hist_add(const char *url, const char *title, unsigned long long when) {
    if (!url || !url[0]) return;
    /* The browser's own pages are not places you have been. Listing about:
     * history inside the history is a mirror facing a mirror. */
    if (!strncmp(url, "about:", 6)) return;

    int at = -1;
    for (int i = 0; i < g_n; i++) if (!strcmp(g_h[i].url, url)) { at = i; break; }
    if (at < 0) {
        if (g_n < HIST_MAX) g_n++;
        at = g_n - 1;                       /* the oldest row, or a new one */
    }
    /* Move it to the top. Revisiting a page must not add a second row: a
     * history where the same address appears forty times is one you cannot
     * read, and reading it is the only thing it is for. */
    for (int i = at; i > 0; i--) g_h[i] = g_h[i - 1];
    snprintf(g_h[0].url, sizeof g_h[0].url, "%s", url);
    snprintf(g_h[0].title, sizeof g_h[0].title, "%s", title ? title : "");
    g_h[0].when = when;
}

int hist_save(void) {
    static char buf[HIST_MAX * (URL_LEN + TITLE_LEN + 32)];
    size_t n = 0;
    for (int i = 0; i < g_n; i++) {
        int w = snprintf(buf + n, sizeof buf - n, "%llu\t%s\t%s\n",
                         g_h[i].when, g_h[i].url, g_h[i].title);
        if (w < 0 || (size_t)w >= sizeof buf - n) break;
        n += (size_t)w;
    }
    return store_put_blob("history.tsv", buf, n);
}

int hist_load(void) {
    static char buf[HIST_MAX * (URL_LEN + TITLE_LEN + 32)];
    long got = store_get_blob("history.tsv", buf, sizeof buf - 1);
    if (got <= 0) return -1;
    buf[got] = 0;
    g_n = 0;
    /* The file is newest-first, and hist_add pushes to the top -- so replaying
     * it in order would invert the list. Walk it backwards. */
    int nlines = 0;
    static char *line[HIST_MAX];
    for (char *l = buf; l && *l && nlines < HIST_MAX; ) {
        line[nlines++] = l;
        char *eol = strchr(l, '\n');
        if (!eol) break;
        *eol = 0;
        l = eol + 1;
    }
    for (int i = nlines - 1; i >= 0; i--) {
        char *t1 = strchr(line[i], '\t');
        if (!t1) continue;
        *t1 = 0;
        char *t2 = strchr(t1 + 1, '\t');
        if (t2) *t2 = 0;
        unsigned long long when = 0;
        for (const char *p = line[i]; *p >= '0' && *p <= '9'; p++)
            when = when * 10 + (unsigned)(*p - '0');
        hist_add(t1 + 1, t2 ? t2 + 1 : "", when);
    }
    return 0;
}

/* Escape the four characters that would otherwise let a page's TITLE inject
 * markup into this document. A title comes off the network; the history page
 * is generated by the browser and parsed by the browser, so without this a
 * hostile <title> would be running script in a page the browser vouched for. */
static size_t esc_html(const char *s, char *out, size_t cap) {
    size_t o = 0;
    for (; s && *s && o + 8 < cap; s++) {
        const char *r = 0;
        switch (*s) {
            case '<': r = "&lt;";  break;
            case '>': r = "&gt;";  break;
            case '&': r = "&amp;"; break;
            case '"': r = "&quot;"; break;
        }
        if (r) { size_t l = strlen(r); memcpy(out + o, r, l); o += l; }
        else out[o++] = *s;
    }
    out[o] = 0;
    return o;
}

size_t hist_as_html(char *out, size_t cap) {
    size_t n = 0;
    n += (size_t)snprintf(out + n, cap - n,
        "<html><head><title>History</title><style>"
        "body{color:#d8d8e0}"
        "h1{color:#8ab4f8}"
        ".when{color:#7a7a88}"
        "li{margin:0 0 10px}"
        "</style></head><body><h1>History</h1>");
    if (g_n == 0)
        n += (size_t)snprintf(out + n, cap - n,
            "<p>Nothing yet. Pages you visit are listed here, newest first.</p>");
    n += (size_t)snprintf(out + n, cap - n, "<ul>");
    for (int i = 0; i < g_n && n + 700 < cap; i++) {
        char t[TITLE_LEN * 6], u[URL_LEN * 6];
        esc_html(g_h[i].title[0] ? g_h[i].title : g_h[i].url, t, sizeof t);
        esc_html(g_h[i].url, u, sizeof u);
        n += (size_t)snprintf(out + n, cap - n,
            "<li><a href=\"%s\">%s</a></li>", u, t);
    }
    n += (size_t)snprintf(out + n, cap - n, "</ul></body></html>");
    return n;
}
