/* user/audio/mp3/tables.h -- the constants ISO 11172-3 defines.
 *
 * Data, not design. A Layer III decoder cannot be written without the
 * standard's Huffman codes, scalefactor band boundaries and synthesis window,
 * and they cannot be derived -- they were chosen and written down. Every
 * independent decoder holds identical copies, exactly as our JPEG decoder
 * holds the tables from T.81.
 *
 * tables.c is GENERATED by tools/mkmp3tables.py, which recovers them from a
 * public-domain reference (PDMP3, Unlicense) and validates every one before
 * emitting it: each table's code must be a complete prefix code (Kraft sum
 * exactly 1) and must hold exactly the number of symbols the standard
 * specifies. That validation is not ceremony -- it caught the reference
 * pointing table 33 at the wrong offset, which would have made every frame
 * using count1 table B decode wrong.
 *
 * The REPRESENTATION here is ours. The reference stores each table as a binary
 * decode tree of 16-bit words with a chained-skip escape; that is its design
 * decision. What the standard actually tabulates is a code, a length and the
 * value pair they mean, so that is what we store -- sorted by length, so the
 * decoder walks lengths upward and stops at the first match, and there is no
 * tree to build or traverse.
 */
#ifndef _EMBLINK_MP3_TABLES_H_
#define _EMBLINK_MP3_TABLES_H_

#include <stdint.h>

/* One Huffman code. `x` and `y` are the quantised value pair; a value of 15
 * in a table with linbits is an ESCAPE, and that many extra magnitude bits
 * follow in the stream. The count1 tables (32, 33) code four values at once
 * and pack them into the four low bits of `y`. */
typedef struct {
    uint16_t code;      /* the code word, right-aligned in `bits` bits */
    uint8_t  bits;      /* its length, 1..19                           */
    uint8_t  x, y;      /* the pair it decodes to                      */
} Mp3HuffEntry;

typedef struct {
    uint16_t start;     /* index into mp3_huff_entries                 */
    uint16_t count;     /* codes in this table (0 = unused table)      */
    uint8_t  linbits;   /* extra magnitude bits after an escape        */
} Mp3HuffTable;

/* Scalefactor band boundaries: where the standard puts the psychoacoustic
 * model's frequency resolution. Requantisation and stereo processing both walk
 * bands rather than raw coefficients, so these are structural, not decorative.
 * `l` is the 22 long-block bands (23 boundaries), `s` the short-block ones. */
typedef struct {
    unsigned l[23];
    unsigned s[14];
} Mp3SfBands;

extern const Mp3HuffEntry mp3_huff_entries[];
extern const Mp3HuffTable mp3_huff_tables[34];
/* Indexed by sample-rate index: 0 = 44100, 1 = 48000, 2 = 32000. */
extern const Mp3SfBands   mp3_sf_bands[3];
extern const float        mp3_synth_window[512];

#endif /* _EMBLINK_MP3_TABLES_H_ */
