#!/usr/bin/env python3
"""pkggen -- the SDK generator (docs/PACKAGING_AND_SDK.md §4, PK2).

ONE package spec -> the THREE views of an app's authority, generated together so
they are consistent BY CONSTRUCTION:
  1. the EMBX      -- its capability table baked in    (via mkembx / EmbLD)
  2. the .ns       -- its namespace manifest           (from the spec's grant)
  3. the .pkg      -- the package manifest             (via mkpkg, re-derived
                      from the EMBX so caps cannot drift)

The spec is the single source of truth: a developer declares authority ONCE and
cannot produce a bundle whose declared authority disagrees with itself -- the
whole point (§4). This is what an SDK's `build.ebm` package stanza will drive.

    pkggen.py <spec.pkgspec> <input.elf> <out-dir>

Spec format (key: value; `#` comments; `grant` may repeat or be comma-separated):
    name:    notes
    version: 1.4.0
    caps:    filesystem network
    grant:   ro /system
    grant:   rw /home/notes
"""
import sys, os, subprocess

def parse_spec(path):
    name = version = None
    caps, grant = [], []
    for raw in open(path):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        key, _, val = line.partition(":")
        key, val = key.strip(), val.strip()
        if   key == "name":    name = val
        elif key == "version": version = val
        elif key == "caps":    caps = [c for c in val.replace(",", " ").split() if c]
        elif key == "grant":
            for g in val.split(","):
                g = g.strip()
                if g:
                    grant.append(g)
        else:
            sys.exit(f"pkggen: unknown spec key '{key}' in {path}")
    if not name or not version:
        sys.exit("pkggen: spec must set both name and version")
    return name, version, caps, grant

def main():
    if len(sys.argv) != 4:
        sys.exit("usage: pkggen.py <spec.pkgspec> <input.elf> <out-dir>")
    spec, elf, outdir = sys.argv[1], sys.argv[2], sys.argv[3]
    name, version, caps, grant = parse_spec(spec)
    here = os.path.dirname(os.path.abspath(__file__))
    embx = os.path.join(outdir, f"{name}.embx")
    nsf  = os.path.join(outdir, f"{name}.ns")
    pkgf = os.path.join(outdir, f"{name}.pkg")

    # 1) EMBX: mkembx/EmbLD bakes the cap table from the spec's caps.
    cap_args = []
    for c in caps:
        cap_args += ["--cap", c.upper()]
    subprocess.run([sys.executable, os.path.join(here, "mkembx.py"), elf, embx] + cap_args, check=True)

    # 2) .ns: the namespace view, straight from the spec's grant.
    with open(nsf, "w") as f:
        f.write(f"# generated by pkggen from {name}'s spec -- one source of truth\n")
        for g in grant:
            f.write(g + "\n")

    # 3) package manifest: mkpkg re-derives caps FROM the EMBX (so the manifest's
    #    caps cannot disagree with the binary) and takes name/version/namespace
    #    from the SAME spec that produced the EMBX and the .ns.
    ns_args = []
    for g in grant:
        ns_args += ["--ns", g]
    subprocess.run([sys.executable, os.path.join(here, "mkpkg.py"), embx, pkgf,
                    "--name", name, "--version", version] + ns_args, check=True)

    print(f"pkggen: {name} v{version} -> {name}.{{embx,ns,pkg}}  "
          f"(caps=[{','.join(caps)}], {len(grant)} grant) -- three consistent views from one spec")

if __name__ == "__main__":
    main()
