#!/usr/bin/env python3
"""Generate the kernel's EmbBuild manifest (build.ebm) for EmbBuild-builds-the-
kernel (docs/BUILD.md §12, KM1). It emits, from the host's KERNEL_SRC list, a
manifest that rebuilds the kernel ON the OS with the on-image embcc + embld:

  * one `compile` stanza per kernel .c   (embcc -c ... -> /data/build/out/kernel/*.o)
  * one `link` stanza                     (embld ... -> /data/build/kernel.elf)

All paths are the ON-IMAGE paths: sources under /data/src/kernel (staged by mkfs,
preserving subdirs, so `-I/data/src/kernel` quote-includes resolve), the pre-built
nasm objects + a kernel_end stub under /data/src/kernel/asm, and outputs under
/data/build (the EmbBuild output tree). Until the on-OS assembler (G1) and EmbLD
`kernel_end` (G2/L1) land, the 6 asm objects and the kernel_end stub are consumed
as PRE-BUILT objects, so only the C compile and the embld link run on the metal.

Usage:  gen_kernel_ebm.py <kernel-src.c> ...   > build.ebm
The .c paths are host paths under kernel/ (as in the Makefile's $(KERNEL_SRC));
they map to /data/src/kernel/<relpath>.
"""
import sys, os

# On-image locations.
SRC   = "/data/src/kernel"                 # staged kernel source tree
ASM   = "/data/src/kernel/asm"             # pre-built nasm objects + kernel_end stub
OUT   = "/data/build/out/kernel"           # per-TU objects EmbBuild produces
CC    = "/data/apps/embcc/embcc.elf"       # the on-OS compiler
LD    = "/data/apps/embld/embld.elf"       # the on-OS linker
INC   = "/data/apps/embcc/include"         # embcc's freestanding headers

# Same codegen flags the host kernel build uses (higher-half, SSE-off, no red zone).
CFLAGS = ["-I" + SRC, "-I" + INC,
          "-mno-sse", "-mno-sse2", "-mno-red-zone", "-mno-mmx",
          "-mcmodel=kernel", "-O2"]

# The pre-built asm objects the link consumes (assembled on the host until G1),
# in the same order as the host link, plus the kernel_end stub (until G2/L1).
ASM_OBJS = ["isr", "syscall_entry", "kcontext", "kentry",
            "ap_entry", "ap_trampoline_blob", "kernel_end"]

KENTRY = "_start"
KBASE  = "0xFFFFFFFF80100000"


def flat(relpath: str) -> str:
    """kernel/mm/pmm.c -> mm_pmm  (a flat, collision-free object stem)."""
    rel = relpath[len("kernel/"):] if relpath.startswith("kernel/") else relpath
    return rel[:-2].replace("/", "_") if rel.endswith(".c") else rel.replace("/", "_")


def main(argv):
    srcs = [a for a in argv[1:] if a.endswith(".c")]
    if not srcs:
        sys.stderr.write("gen_kernel_ebm: no .c sources given\n")
        return 2

    out = []
    out.append("# GENERATED by tools/gen_kernel_ebm.py -- do not hand-edit.")
    out.append("# EmbBuild-builds-the-kernel (docs/BUILD.md §12, KM1): rebuild the")
    out.append("# kernel ON the OS with the on-image embcc + embld.")
    out.append("project: kernel")
    out.append("")

    objs = []
    for s in sorted(srcs):
        rel = s[len("kernel/"):] if s.startswith("kernel/") else s
        stem = flat(s)
        obj = f"{OUT}/{stem}.o"
        objs.append(obj)
        out.append(f"name: {stem}.o")
        out.append("kind: compile")
        out.append(f"inputs: {SRC}/{rel}")
        out.append(f"args: {CC} -c {SRC}/{rel} " + " ".join(CFLAGS) + f" -o {obj}")
        out.append(f"output: {obj}")
        out.append("")

    asm_objs = [f"{ASM}/{a}.o" for a in ASM_OBJS]
    link_inputs = objs + asm_objs
    out.append("name: kernel.elf")
    out.append("kind: link")
    out.append("inputs: " + " ".join(link_inputs))
    out.append(f"args: {LD} -e {KENTRY} -Ttext {KBASE} -o /data/build/kernel.elf "
               + " ".join(link_inputs))
    out.append("output: /data/build/kernel.elf")
    out.append("")

    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
